config/routes.rb
Rails.application.routes.draw do
  # get 'games', to: "games#index"

  # get 'games/:id', to: "games#show", as: "game"

  # get 'games/new', to: "games#new"

  # post 'games', to: "games#create"

  # get 'games/:id/edit', to: "games#edit"

  # patch 'games/:id', to: "games#update"

  # delete 'games/:id', to: "games#destroy"

  resources :games # writing this do all the above, and create prefixes automatically
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.save
    redirect_to game_path(@game)
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)

    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :genre, :format, :msrp, :multiplayer, :release_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.label :format %>
  <%= f.text_field :format %>
  <%= f.label :msrp %>
  <%= f.text_field :msrp %>
  <%= f.label :multiplayer %>
  <%= f.text_field :multiplayer %>
  <%= f.label :release_date %>
  <%= f.text_field :release_date %>
  <%= f.submit %>
<% end %>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

<%= link_to "Delete", game_path(game), method: :delete, data: { confirm: "Are your sure?" } %>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

<%= render "form" %>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

<% @games.each do |game| %>
<h3><%= "#{game.name} | "%><em><%= "#{game.genre}"%></em></h3>
<%= link_to "#{game.name} page", game_path(game) %>
<%= link_to "Edit", edit_game_path(game) %>
<%= link_to "Delete Entry", game_path(game), method: :delete %>
<%= link_to "Create New Game", new_game_path(game) %>
<ul>
  <li>
    <em><%="Format: "%></em><strong><%="#{game.format}" %></strong>
  </li>
  <li>
    <em><%="Price: "%></em><strong><%="#{game.msrp}" %></strong>
  </li>
  <li>
    <em><%="Multiplayer: "%></em><strong><%="#{game.multiplayer}" %></strong>
  </li>
  <li>
    <em><%="Release Date: "%></em><strong><%="#{game.release_date}" %></strong>
  </li>
</ul>
<% end %>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

<%= render "form" %>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

<h2><%= @game.name %></h2>
<p><%= @game.genre %></p>
<p><%= @game.format %></p>


<%= link_to "Back to Games list", games_path %>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>